# Data Cleaning Practice
University of Denver

Makarand Nadendla

In [238]:
import pandas as pd
import numpy as np
from scipy.stats import skew

In [247]:
# csv import
boston_1 = pd.read_csv("boston_weather_1.csv")
boston_2 = pd.read_csv("boston_weather_2.csv")
boston_3 = pd.read_csv("boston_weather_3.csv")
boston_4 = pd.read_csv("boston_weather_4.csv")
more_variables = pd.read_csv("more_weather_variables.csv")

# concatenation
combined_boston = pd.concat([boston_1,boston_2,boston_3,boston_4])
combined_boston.reset_index(drop = True, inplace = True)
combined_boston = pd.concat([combined_boston, more_variables], axis = 1)
print(f"\nShape: {combined_boston.shape}")


Shape: (1140, 13)


In [71]:
# head
combined_boston.head()

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
0      1  1920      -8.0       48.0         37.0          12.0     12.5   
1      2  1920      -7.0       52.0         34.0          16.0     20.6   
2      3  1920      10.0       72.0         45.0          25.0     30.5   
3      4  1920      26.0       67.0         46.0          37.0     38.0   
4      5  1920      36.0       86.0         61.0          45.0     47.5   

   ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
0     29.5       21.0        2.72     24.8             0.74           6.7  
1     34.6       27.6        4.11     32.5             1.01          12.2  
2     48.0       39.3        3.72       11             1.15             6  
3     52.1       45.1        5.68        2             1.19             2  
4     61.8       54.6        5.26        0             3.23             0

In [44]:
# tail
combined_boston.tail()

Month  Year  LowTemp  HighTemp  WarmestMin  ColdestHigh  AveMin  AveMax  \
1135      8  2014     58.0      91.0        70.0         69.0    63.2    78.4   
1136      9  2014     46.0      93.0        72.0         56.0    58.3    74.2   
1137     10  2014     39.0      81.0        61.0         52.0    49.7    63.0   
1138     11  2014     23.0      66.0        48.0         34.0    35.5    49.5   
1139     12  2014     18.0      64.0        44.0         29.0    32.8    43.7   

      meanTemp  TotPrecip TotSnow  Max24hrPrecip Max24hrSnow  
1135      70.8       1.75       0           1.06           0  
1136      66.2       0.70       0           0.22           0  
1137      56.4       5.83       0           2.25           0  
1138      42.5       5.27     2.6           1.64         2.3  
1139      38.3       6.56     0.3           2.90         0.3

In [53]:
# NA values per column
combined_boston.isna().sum(axis=0)

Month            0
Year             0
LowTemp          6
HighTemp         5
WarmestMin       6
ColdestHigh      9
AveMin           3
AveMax           6
meanTemp         0
TotPrecip        0
TotSnow          0
Max24hrPrecip    0
Max24hrSnow      0
dtype: int64

In [67]:
# Dropping NA values per column
clean_boston_data = combined_boston.dropna(axis = 0)
print(clean_boston_data.isna().sum(axis=0))
print(f"\nShape: {clean_boston_data.shape}")

month              0
year               0
low_temp           0
high_temp          0
warmest_min        0
coldest_high       0
ave_min            0
ave_max            0
mean_temp          0
tot_precip         0
tot_snow           0
max_24hr_precip    0
max_24hr_snow      0
dtype: int64

Shape: (1112, 13)


In [68]:
# column name change
clean_boston_data.columns=['month',
 'year',
 'low_temp',
 'high_temp',
 'warmest_min',
 'coldest_high',
 'ave_min',
 'ave_max',
 'mean_temp',
 'tot_precip',
 'tot_snow',
 'max_24hr_precip',
 'max_24hr_snow']
clean_boston_data.columns

Index(['month', 'year', 'low_temp', 'high_temp', 'warmest_min', 'coldest_high',
       'ave_min', 'ave_max', 'mean_temp', 'tot_precip', 'tot_snow',
       'max_24hr_precip', 'max_24hr_snow'],
      dtype='object')

In [81]:
# excluding 1930 unique vals
excluding_1930 = clean_boston_data[~(clean_boston_data["year"]==1930)]
excluding_1930["year"].unique()[:20]

array([1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1931,
       1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940], dtype=int64)

In [82]:
# year is 1995 and high_temp is greater than or equal to 90
clean_boston_data[(clean_boston_data["year"]==1995)&(clean_boston_data["high_temp"]>=90)]

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
905      6  1995      53.0       95.0         73.0          61.0     60.2   
906      7  1995      59.0      100.0         75.0          67.0     67.1   
907      8  1995      55.0       96.0         72.0          66.0     64.1   

     ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
905     77.0       68.6        1.55        0             0.53             0  
906     84.6       75.9        2.06        0             0.88             0  
907     81.5       72.8        0.82        0             0.63             0

In [90]:
# year is and 1995 OR the high_temp is greater than 89 (First 20 rows)
clean_boston_data[(clean_boston_data["year"]==1995)|(clean_boston_data["high_temp"]>=89)][:20]

month  year  low_temp  high_temp  warmest_min  coldest_high  ave_min  \
6       7  1920      56.0       90.0         71.0          65.0     63.4   
7       8  1920      56.0       93.0         74.0          69.0     65.2   
16      5  1921      41.0       93.0         70.0          48.0     50.0   
19      8  1921      55.0       92.0         72.0          69.0     61.5   
20      9  1921      53.0       93.0         75.0          64.0     60.1   
29      6  1922      52.0       92.0         72.0          59.0     60.8   
30      7  1922      58.0       93.0         72.0          64.0     64.4   
31      8  1922      54.0       93.0         72.0          65.0     63.4   
40      5  1923      35.0       89.0         65.0          52.0     48.6   
41      6  1923      47.0       96.0         74.0          53.0     59.6   
42      7  1923      56.0       94.0         72.0          62.0     62.2   
43      8  1923      51.0       94.0         74.0          63.0     60.5   
53      6  1924      48.0       90.0         68.0          58.0     58.2   
54      7  1924      58.0       95.0         73.0          68.0     64.8   
55      8  1924      56.0       98.0         75.0          68.0     64.4   
56      9  1924      44.0       90.0         71.0          59.0     54.4   
65      6  1925      53.0      100.0         80.0          59.0     61.1   
66      7  1925      54.0       95.0         73.0          66.0     64.1   
67      8  1925      50.0       92.0         70.0          67.0     62.3   
68      9  1925      41.0       90.0         72.0          56.0     56.0   

    ave_max  mean_temp  tot_precip tot_snow  max_24hr_precip max_24hr_snow  
6      81.4       72.4        1.56        0             0.76             0  
7      78.9       72.0        2.32        0             1.00             0  
16     66.1       58.0        3.63        0             1.82             0  
19     77.7       69.6        1.63        0             1.12             0  
20     76.9       68.5        1.22        0             0.36             0  
29     76.5       68.7        8.05        0             3.32             0  
30     79.7       72.0        2.63        0             0.86             0  
31     77.4       70.4        4.75        0             1.23             0  
40     66.5       57.6        0.83        0             0.37             0  
41     79.0       69.3        2.03        0             1.02             0  
42     77.7       69.9        3.36        0             0.78             0  
43     78.1       69.3        2.07        0             0.78             0  
53     75.1       66.7        1.07        0             0.36             0  
54     82.9       73.8        2.04        0             0.70             0  
55     79.5       71.9        6.86        0             4.15             0  
56     70.0       62.2        6.96        0             3.89             0  
65     80.7       70.9        4.59        0             1.36             0  
66     80.5       72.3        3.54        0             1.19             0  
67     80.0       71.1        1.40        0             0.47             0  
68     72.1       64.1        3.45        0             1.46             0

In [135]:
# read in the data and drop the first column
student_data = pd.read_excel("student_data.xlsx")
student_data.drop("Unnamed: 0", axis = 1, inplace = True)
student_data.head()

ice_cream_flavor  math  reading  science 
0          vanilla    90       82        90
1      chocollate    100       73        92
2          vanilla    80       92        95
3      strawberry     95      100        82
4      strawberry     90       79        81

In [158]:
#flavor and scores
flavors = np.array(student_data["ice_cream_flavor"])
scores = np.array(student_data[["math","reading","science "]])
flavors, scores

(array(['vanilla', 'chocollate ', 'vanilla', 'strawberry ', 'strawberry ',
        'chocollate ', 'vanilla', 'vanilla', 'chocollate ', 'chocollate ',
        'vanilla', 'strawberry ', 'strawberry ', 'chocollate ', 'vanilla',
        'vanilla'], dtype=object),
 array([[ 90,  82,  90],
        [100,  73,  92],
        [ 80,  92,  95],
        [ 95, 100,  82],
        [ 90,  79,  81],
        [ 90,  90,  90],
        [100,  89,  91],
        [ 80,  85,  79],
        [ 85,  99,  85],
        [100,  73,  92],
        [ 80,  92,  95],
        [ 95, 100,  82],
        [ 90,  79,  81],
        [ 86,  92,  90],
        [100,  89,  89],
        [ 83,  95,  79]], dtype=int64))

In [159]:
# chocolate
scores[flavors == "chocollate "]

array([[100,  73,  92],
       [ 90,  90,  90],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 86,  92,  90]], dtype=int64)

In [160]:
# chocolate or vanilla
scores[(flavors == "chocollate ") | (flavors == "vanilla")]

array([[ 90,  82,  90],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 90,  90,  90],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 85,  99,  85],
       [100,  73,  92],
       [ 80,  92,  95],
       [ 86,  92,  90],
       [100,  89,  89],
       [ 83,  95,  79]], dtype=int64)

In [161]:
# not chocolate
scores[~(flavors == "chocollate ")]

array([[ 90,  82,  90],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  91],
       [ 80,  85,  79],
       [ 80,  92,  95],
       [ 95, 100,  82],
       [ 90,  79,  81],
       [100,  89,  89],
       [ 83,  95,  79]], dtype=int64)

In [163]:
# mean of scores with their favorite ice cream flavor as chocolate
scores[flavors == "chocollate "][:,:2].mean(axis = 0)

array([92.2, 85.4])

In [228]:
from sklearn.preprocessing import LabelBinarizer, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

In [220]:
# binarized ice cream labels
encoded = LabelBinarizer()
encoded_df = pd.DataFrame(encoded.fit_transform(student_data["ice_cream_flavor"]), columns = encoded.classes_)
student_data_1 = pd.concat([student_data, encoded_df], axis = 1)
student_data_1.drop("ice_cream_flavor", axis = 1, inplace = True)
student_data_1.columns

Index(['math', 'reading', 'science ', 'chocollate ', 'strawberry ', 'vanilla'], dtype='object')

In [224]:
# different scalers for different scores
scaler = StandardScaler()

std_df = pd.DataFrame(scaler.fit_transform(student_data_1[["math", "reading", "science "]]), columns = ["math", "reading", "science"])
student_data_std = student_data_1.drop(["math", "reading", "science "], axis = 1)
student_data_std = pd.concat([student_data_std, std_df], axis = 1)
student_data_std

chocollate   strawberry   vanilla      math   reading   science
0             0            0        1 -0.034524 -0.709277  0.536906
1             1            0        0  1.346430 -1.762225  0.902459
2             0            0        1 -1.415477  0.460665  1.450789
3             0            1        0  0.655953  1.396618 -0.925306
4             0            1        0 -0.034524 -1.060260 -1.108083
5             1            0        0 -0.034524  0.226676  0.536906
6             0            0        1  1.346430  0.109682  0.719683
7             0            0        1 -1.415477 -0.358295 -1.473636
8             1            0        0 -0.725001  1.279624 -0.376977
9             1            0        0  1.346430 -1.762225  0.902459
10            0            0        1 -1.415477  0.460665  1.450789
11            0            1        0  0.655953  1.396618 -0.925306
12            0            1        0 -0.034524 -1.060260 -1.108083
13            1            0        0 -0.586905  0.460665  0.536906
14            0            0        1  1.346430  0.109682  0.354130
15            0            0        1 -1.001191  0.811647 -1.473636

In [223]:
# split data
X = student_data_std.drop('science',axis = 1)
y = student_data_std["science"]
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size = 0.3)

In [237]:
pipeline = Pipeline([('scaler', MinMaxScaler()), ('imputer', SimpleImputer(missing_values=np.nan, strategy='mean'))])
pipeline_data = pd.DataFrame(pipeline.fit_transform(boston_1[["LowTemp", "HighTemp", "WarmestMin", "ColdestHigh", "AveMin", "AveMax"]]
, ), columns = ["LowTemp", "HighTemp", "WarmestMin", "ColdestHigh", "AveMin", "AveMax"])

LowTemp  HighTemp  WarmestMin  ColdestHigh    AveMin    AveMax
0    0.128205  0.067797    0.156863     0.126761  0.078231  0.041958
1    0.141026  0.135593    0.098039     0.183099  0.215986  0.131119
2    0.358974  0.474576    0.313725     0.309859  0.384354  0.365385
3    0.564103  0.389831    0.333333     0.478873  0.511905  0.437063
4    0.692308  0.711864    0.627451     0.591549  0.673469  0.606643
..        ...       ...         ...          ...       ...       ...
295  0.910256  0.966102    0.921569     0.929577  0.972789  1.000000
296  0.769231  0.779661    0.803922     0.788732  0.840136  0.797203
297  0.615385  0.711864    0.686275     0.591549  0.637755  0.611888
298  0.602564  0.423729    0.372549     0.450704  0.479592  0.403846
299  0.333333  0.101695    0.137255     0.239437  0.263605  0.194056

[300 rows x 6 columns]

In [245]:
def desc_statistics(vec):
    mean = np.mean(vec)
    median = np.median(vec)
    std = np.std(vec)
    var = np.var(vec)
    minmum = min(vec)
    maxmum = max(vec)
    skews = skew(vec)
    
    print(vec.name)
    print(f"Mean: {mean}, Median: {median},\nStdev: {std}, Variance: {var},\nMin: {minmum}, Max: {maxmum}, \nSkewness: {skews}")
    print()
pipeline_data.apply(desc_statistics, axis = 0)

LowTemp
Mean: 0.6035105833763553, Median: 0.6094475993804853,
Stdev: 0.2494969471288789, Variance: 0.0622487266266306,
Min: 0.0, Max: 0.9999999999999999, 
Skewness: -0.16809370647798735

HighTemp
Mean: 0.5524738914569424, Median: 0.5847457627118644,
Stdev: 0.26428273772906097, Variance: 0.06984536546156764,
Min: 0.0, Max: 1.0, 
Skewness: -0.354788400276893

WarmestMin
Mean: 0.534264541937176, Median: 0.5490196078431373,
Stdev: 0.2683952185861344, Variance: 0.07203599335989887,
Min: 0.0, Max: 1.0, 
Skewness: -0.16819293567803056

ColdestHigh
Mean: 0.5500143719459613, Median: 0.5496550732969243,
Stdev: 0.24709411436030332, Variance: 0.06105550135150266,
Min: 0.0, Max: 1.0, 
Skewness: -0.06674918248225123

AveMin
Mean: 0.5946201814058962, Median: 0.586734693877551,
Stdev: 0.26046707983813067, Variance: 0.06784309967940315,
Min: 0.0, Max: 0.9999999999999999, 
Skewness: -0.07814411582902162

AveMax
Mean: 0.5508279346071991, Median: 0.5516377435273756,
Stdev: 0.2820290135007337, Variance: 0.

LowTemp        None
HighTemp       None
WarmestMin     None
ColdestHigh    None
AveMin         None
AveMax         None
dtype: object